// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: esp32-c6

#include "../ui.h"

void ui_loadScr_screen_init(void)
{
ui_loadScr = lv_obj_create(NULL);
lv_obj_clear_flag( ui_loadScr, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_loadScr, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_loadScr, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_loadIDImg = lv_img_create(ui_loadScr);
lv_img_set_src(ui_loadIDImg, &ui_img_id_img_png);
lv_obj_set_width( ui_loadIDImg, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_loadIDImg, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_loadIDImg, 0 );
lv_obj_set_y( ui_loadIDImg, -50 );
lv_obj_set_align( ui_loadIDImg, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_loadIDImg, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_loadIDImg, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_loadBar = lv_bar_create(ui_loadScr);
lv_bar_set_value(ui_loadBar,25,LV_ANIM_OFF);
lv_bar_set_start_value(ui_loadBar, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_loadBar, 172);
lv_obj_set_height( ui_loadBar, 10);
lv_obj_set_x( ui_loadBar, 0 );
lv_obj_set_y( ui_loadBar, -5 );
lv_obj_set_align( ui_loadBar, LV_ALIGN_BOTTOM_MID );

ui_loadIDLabel = lv_label_create(ui_loadScr);
lv_obj_set_width( ui_loadIDLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_loadIDLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_loadIDLabel, 0 );
lv_obj_set_y( ui_loadIDLabel, 15 );
lv_obj_set_align( ui_loadIDLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_loadIDLabel,"我是大柴啊");
lv_label_set_recolor(ui_loadIDLabel,"true");
lv_obj_set_style_text_color(ui_loadIDLabel, lv_color_hex(0xDC74E4), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_loadIDLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_loadIDLabel, &ui_font_zh_16_bpp4, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_loadMsg = lv_label_create(ui_loadScr);
lv_obj_set_width( ui_loadMsg, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_loadMsg, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_loadMsg, 36 );
lv_obj_set_y( ui_loadMsg, -19 );
lv_obj_set_align( ui_loadMsg, LV_ALIGN_BOTTOM_LEFT );
lv_label_set_text(ui_loadMsg,"初始化");
lv_obj_set_style_text_font(ui_loadMsg, &ui_font_zh_14_bpp4, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_loadBar, ui_event_loadBar, LV_EVENT_ALL, NULL);
uic_loadScr = ui_loadScr;
uic_loadIDImg = ui_loadIDImg;
uic_loadBar = ui_loadBar;
uic_loadIDLabel = ui_loadIDLabel;
uic_loadMsg = ui_loadMsg;

}
