// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: esp32-c6

#include "../ui.h"

void ui_mainScr_screen_init(void)
{
ui_mainScr = lv_obj_create(NULL);
lv_obj_clear_flag( ui_mainScr, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_img_src( ui_mainScr, &ui_img_bg_2_png, LV_PART_MAIN | LV_STATE_DEFAULT );

ui_mainTopCon = lv_obj_create(ui_mainScr);
lv_obj_remove_style_all(ui_mainTopCon);
lv_obj_set_width( ui_mainTopCon, 172);
lv_obj_set_height( ui_mainTopCon, 20);
lv_obj_set_x( ui_mainTopCon, 0 );
lv_obj_set_y( ui_mainTopCon, -150 );
lv_obj_set_align( ui_mainTopCon, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_mainTopCon, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_mainTopCon, lv_color_hex(0xC27BDA), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_mainTopCon, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_mainTopCon, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_mainTopCon, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_mainTopCon, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_mainTopCon, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_mainTopCon, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_mainTopCon, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_mainTopTimeLable = lv_label_create(ui_mainTopCon);
lv_obj_set_width( ui_mainTopTimeLable, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_mainTopTimeLable, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_mainTopTimeLable, 5 );
lv_obj_set_y( ui_mainTopTimeLable, 0 );
lv_obj_set_align( ui_mainTopTimeLable, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_mainTopTimeLable,"2025/2/23|24:59:59");
lv_obj_set_style_text_color(ui_mainTopTimeLable, lv_color_hex(0xF4EAEA), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_mainTopTimeLable, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_mainTopTimeLable, &ui_font_zh_14_bpp4, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_mainTopWifiIcon = lv_img_create(ui_mainTopCon);
lv_img_set_src(ui_mainTopWifiIcon, &ui_img_wifi_1_png);
lv_obj_set_width( ui_mainTopWifiIcon, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_mainTopWifiIcon, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_mainTopWifiIcon, -3 );
lv_obj_set_y( ui_mainTopWifiIcon, 0 );
lv_obj_set_align( ui_mainTopWifiIcon, LV_ALIGN_RIGHT_MID );
lv_obj_add_flag( ui_mainTopWifiIcon, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_mainTopWifiIcon, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_mainDataCon = lv_obj_create(ui_mainScr);
lv_obj_remove_style_all(ui_mainDataCon);
lv_obj_set_width( ui_mainDataCon, 172);
lv_obj_set_height( ui_mainDataCon, 200);
lv_obj_set_align( ui_mainDataCon, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_mainDataCon, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_left(ui_mainDataCon, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_mainDataCon, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_mainDataCon, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_mainDataCon, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_mainDataCon, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_mainDataCon, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_mainDataViewlabel = lv_label_create(ui_mainDataCon);
lv_obj_set_width( ui_mainDataViewlabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_mainDataViewlabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_mainDataViewlabel, 0 );
lv_obj_set_y( ui_mainDataViewlabel, 19 );
lv_obj_set_align( ui_mainDataViewlabel, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_mainDataViewlabel,"我还没想好这里装什么");
lv_obj_set_style_text_color(ui_mainDataViewlabel, lv_color_hex(0xC92222), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_mainDataViewlabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_mainDataViewlabel, &ui_font_zh_16_bpp4, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_mainBotCon = lv_obj_create(ui_mainScr);
lv_obj_remove_style_all(ui_mainBotCon);
lv_obj_set_width( ui_mainBotCon, 172);
lv_obj_set_height( ui_mainBotCon, 50);
lv_obj_set_align( ui_mainBotCon, LV_ALIGN_BOTTOM_MID );
lv_obj_clear_flag( ui_mainBotCon, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_mainBotCpuLabel = lv_label_create(ui_mainBotCon);
lv_obj_set_width( ui_mainBotCpuLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_mainBotCpuLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_mainBotCpuLabel, 2 );
lv_obj_set_y( ui_mainBotCpuLabel, 5 );
lv_label_set_text(ui_mainBotCpuLabel,"CPU负载：");
lv_obj_set_style_text_color(ui_mainBotCpuLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_mainBotCpuLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_mainBotCpuLabel, &ui_font_zh__8_bpp8, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_mainBotBarCpu = lv_bar_create(ui_mainBotCon);
lv_bar_set_value(ui_mainBotBarCpu,25,LV_ANIM_OFF);
lv_bar_set_start_value(ui_mainBotBarCpu, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_mainBotBarCpu, 130);
lv_obj_set_height( ui_mainBotBarCpu, 10);
lv_obj_set_x( ui_mainBotBarCpu, 16 );
lv_obj_set_y( ui_mainBotBarCpu, 5 );
lv_obj_set_align( ui_mainBotBarCpu, LV_ALIGN_TOP_MID );

ui_mainBotFpsLable = lv_label_create(ui_mainBotCon);
lv_obj_set_width( ui_mainBotFpsLable, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_mainBotFpsLable, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_mainBotFpsLable, 12 );
lv_obj_set_y( ui_mainBotFpsLable, 32 );
lv_label_set_text(ui_mainBotFpsLable,"FPS：");
lv_obj_set_style_text_color(ui_mainBotFpsLable, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_mainBotFpsLable, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_mainBotFpsLable, &ui_font_zh__8_bpp8, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_mainBotBarFps = lv_bar_create(ui_mainBotCon);
lv_bar_set_value(ui_mainBotBarFps,25,LV_ANIM_OFF);
lv_bar_set_start_value(ui_mainBotBarFps, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_mainBotBarFps, 130);
lv_obj_set_height( ui_mainBotBarFps, 10);
lv_obj_set_x( ui_mainBotBarFps, 16 );
lv_obj_set_y( ui_mainBotBarFps, 31 );
lv_obj_set_align( ui_mainBotBarFps, LV_ALIGN_TOP_MID );

ui_mainGifCon = lv_obj_create(ui_mainScr);
lv_obj_remove_style_all(ui_mainGifCon);
lv_obj_set_width( ui_mainGifCon, 172);
lv_obj_set_height( ui_mainGifCon, 35);
lv_obj_set_x( ui_mainGifCon, 0 );
lv_obj_set_y( ui_mainGifCon, 21 );
lv_obj_set_align( ui_mainGifCon, LV_ALIGN_TOP_MID );
lv_obj_clear_flag( ui_mainGifCon, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_mainGifLabel = lv_label_create(ui_mainGifCon);
lv_obj_set_width( ui_mainGifLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_mainGifLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_mainGifLabel, 16 );
lv_obj_set_y( ui_mainGifLabel, 0 );
lv_obj_set_align( ui_mainGifLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_mainGifLabel,"大佬们给个关注啊");
lv_label_set_recolor(ui_mainGifLabel,"true");
lv_obj_set_style_text_color(ui_mainGifLabel, lv_color_hex(0xEE1942), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_mainGifLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_mainGifLabel, &ui_font_zh_16_bpp4, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_mainGifImg = lv_img_create(ui_mainGifCon);
lv_img_set_src(ui_mainGifImg, &ui_img_gif_0_png);
lv_obj_set_width( ui_mainGifImg, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_mainGifImg, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_mainGifImg, -66 );
lv_obj_set_y( ui_mainGifImg, 0 );
lv_obj_set_align( ui_mainGifImg, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_mainGifImg, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_mainGifImg, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

uic_mainScr = ui_mainScr;
uic_mainTopCon = ui_mainTopCon;
uic_mainTopTimeLable = ui_mainTopTimeLable;
uic_mainTopWifiIcon = ui_mainTopWifiIcon;
uic_mainDataCon = ui_mainDataCon;
uic_mainDataViewlabel = ui_mainDataViewlabel;
uic_mainBotCon = ui_mainBotCon;
uic_mainBotCpuLabel = ui_mainBotCpuLabel;
uic_mainBotBarCpu = ui_mainBotBarCpu;
uic_mainBotFpsLable = ui_mainBotFpsLable;
uic_mainBotBarFps = ui_mainBotBarFps;
uic_mainGifCon = ui_mainGifCon;
uic_mainGifLabel = ui_mainGifLabel;
uic_mainGifImg = ui_mainGifImg;

}
