// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: esp32-c6

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
void loadBarAnim_Animation( lv_obj_t *TargetObject, int delay);
void mainBotBarAnim_Animation( lv_obj_t *TargetObject, int delay);


// SCREEN: ui_loadScr
void ui_loadScr_screen_init(void);
lv_obj_t *ui_loadScr;
lv_obj_t *ui_loadIDImg;
void ui_event_loadBar( lv_event_t * e);
lv_obj_t *ui_loadBar;
lv_obj_t *ui_loadIDLabel;
lv_obj_t *ui_loadMsg;
// CUSTOM VARIABLES
lv_obj_t *uic_loadScr;
lv_obj_t *uic_loadIDImg;
lv_obj_t *uic_loadBar;
lv_obj_t *uic_loadIDLabel;
lv_obj_t *uic_loadMsg;


// SCREEN: ui_mainScr
void ui_mainScr_screen_init(void);
lv_obj_t *ui_mainScr;
lv_obj_t *ui_mainTopCon;
lv_obj_t *ui_mainTopTimeLable;
lv_obj_t *ui_mainTopWifiIcon;
lv_obj_t *ui_mainDataCon;
lv_obj_t *ui_mainDataViewlabel;
lv_obj_t *ui_mainBotCon;
lv_obj_t *ui_mainBotCpuLabel;
lv_obj_t *ui_mainBotBarCpu;
lv_obj_t *ui_mainBotFpsLable;
lv_obj_t *ui_mainBotBarFps;
lv_obj_t *ui_mainGifCon;
lv_obj_t *ui_mainGifLabel;
lv_obj_t *ui_mainGifImg;
// CUSTOM VARIABLES
lv_obj_t *uic_mainScr;
lv_obj_t *uic_mainTopCon;
lv_obj_t *uic_mainTopTimeLable;
lv_obj_t *uic_mainTopWifiIcon;
lv_obj_t *uic_mainDataCon;
lv_obj_t *uic_mainDataViewlabel;
lv_obj_t *uic_mainBotCon;
lv_obj_t *uic_mainBotCpuLabel;
lv_obj_t *uic_mainBotBarCpu;
lv_obj_t *uic_mainBotFpsLable;
lv_obj_t *uic_mainBotBarFps;
lv_obj_t *uic_mainGifCon;
lv_obj_t *uic_mainGifLabel;
lv_obj_t *uic_mainGifImg;

// EVENTS
lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
const lv_img_dsc_t *ui_imgset_bg_[2] = {&ui_img_bg_1_png, &ui_img_bg_2_png};
const lv_img_dsc_t *ui_imgset_wifi_[4] = {&ui_img_wifi_1_png, &ui_img_wifi_2_png, &ui_img_wifi_3_png, &ui_img_wifi_4_png};
const lv_img_dsc_t *ui_imgset_gif_[11] = {&ui_img_gif_0_png, &ui_img_gif_1_png, &ui_img_gif_2_png, &ui_img_gif_3_png, &ui_img_gif_4_png, &ui_img_gif_5_png, &ui_img_gif_6_png, &ui_img_gif_7_png, &ui_img_gif_8_png, &ui_img_gif_9_png, &ui_img_gif_10_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////
void loadBarAnim_Animation( lv_obj_t *TargetObject, int delay)
{

}
void mainBotBarAnim_Animation( lv_obj_t *TargetObject, int delay)
{
ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_0_user_data->target = TargetObject;
PropertyAnimation_0_user_data->val = -1;
lv_anim_t PropertyAnimation_0;
lv_anim_init(&PropertyAnimation_0);
lv_anim_set_time(&PropertyAnimation_0, 1000);
lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_x );
lv_anim_set_values(&PropertyAnimation_0, 0, 100 );
lv_anim_set_path_cb( &PropertyAnimation_0, lv_anim_path_linear);
lv_anim_set_delay( &PropertyAnimation_0, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_0, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_0, 0);
lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
lv_anim_set_early_apply( &PropertyAnimation_0, false );
 lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_x );
lv_anim_start(&PropertyAnimation_0);

}

///////////////////// FUNCTIONS ////////////////////
void ui_event_loadBar( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      _ui_bar_set_property(ui_loadBar, _UI_BAR_PROPERTY_VALUE_WITH_ANIM, 50);
}
}

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), true, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_loadScr_screen_init();
ui_mainScr_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_loadScr);
}
