// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: esp32-c6

#ifndef _ESP32_C6_UI_H
#define _ESP32_C6_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

void loadBarAnim_Animation( lv_obj_t *TargetObject, int delay);
void mainBotBarAnim_Animation( lv_obj_t *TargetObject, int delay);

// SCREEN: ui_loadScr
void ui_loadScr_screen_init(void);
extern lv_obj_t *ui_loadScr;
extern lv_obj_t *ui_loadIDImg;
void ui_event_loadBar( lv_event_t * e);
extern lv_obj_t *ui_loadBar;
extern lv_obj_t *ui_loadIDLabel;
extern lv_obj_t *ui_loadMsg;
// CUSTOM VARIABLES
extern lv_obj_t *uic_loadScr;
extern lv_obj_t *uic_loadIDImg;
extern lv_obj_t *uic_loadBar;
extern lv_obj_t *uic_loadIDLabel;
extern lv_obj_t *uic_loadMsg;

// SCREEN: ui_mainScr
void ui_mainScr_screen_init(void);
extern lv_obj_t *ui_mainScr;
extern lv_obj_t *ui_mainTopCon;
extern lv_obj_t *ui_mainTopTimeLable;
extern lv_obj_t *ui_mainTopWifiIcon;
extern lv_obj_t *ui_mainDataCon;
extern lv_obj_t *ui_mainDataViewlabel;
extern lv_obj_t *ui_mainBotCon;
extern lv_obj_t *ui_mainBotCpuLabel;
extern lv_obj_t *ui_mainBotBarCpu;
extern lv_obj_t *ui_mainBotFpsLable;
extern lv_obj_t *ui_mainBotBarFps;
extern lv_obj_t *ui_mainGifCon;
extern lv_obj_t *ui_mainGifLabel;
extern lv_obj_t *ui_mainGifImg;
// CUSTOM VARIABLES
extern lv_obj_t *uic_mainScr;
extern lv_obj_t *uic_mainTopCon;
extern lv_obj_t *uic_mainTopTimeLable;
extern lv_obj_t *uic_mainTopWifiIcon;
extern lv_obj_t *uic_mainDataCon;
extern lv_obj_t *uic_mainDataViewlabel;
extern lv_obj_t *uic_mainBotCon;
extern lv_obj_t *uic_mainBotCpuLabel;
extern lv_obj_t *uic_mainBotBarCpu;
extern lv_obj_t *uic_mainBotFpsLable;
extern lv_obj_t *uic_mainBotBarFps;
extern lv_obj_t *uic_mainGifCon;
extern lv_obj_t *uic_mainGifLabel;
extern lv_obj_t *uic_mainGifImg;

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE( ui_img_id_img_png);   // assets/id_img.png
LV_IMG_DECLARE( ui_img_bg_2_png);   // assets/bg_2.png
LV_IMG_DECLARE( ui_img_wifi_1_png);   // assets/wifi_1.png
LV_IMG_DECLARE( ui_img_gif_0_png);   // assets/gif_0.png
LV_IMG_DECLARE( ui_img_bg_1_png);   // assets/bg_1.png
LV_IMG_DECLARE( ui_img_wifi_2_png);   // assets/wifi_2.png
LV_IMG_DECLARE( ui_img_wifi_3_png);   // assets/wifi_3.png
LV_IMG_DECLARE( ui_img_wifi_4_png);   // assets/wifi_4.png
LV_IMG_DECLARE( ui_img_gif_1_png);   // assets/gif_1.png
LV_IMG_DECLARE( ui_img_gif_2_png);   // assets/gif_2.png
LV_IMG_DECLARE( ui_img_gif_3_png);   // assets/gif_3.png
LV_IMG_DECLARE( ui_img_gif_4_png);   // assets/gif_4.png
LV_IMG_DECLARE( ui_img_gif_5_png);   // assets/gif_5.png
LV_IMG_DECLARE( ui_img_gif_6_png);   // assets/gif_6.png
LV_IMG_DECLARE( ui_img_gif_7_png);   // assets/gif_7.png
LV_IMG_DECLARE( ui_img_gif_8_png);   // assets/gif_8.png
LV_IMG_DECLARE( ui_img_gif_9_png);   // assets/gif_9.png
LV_IMG_DECLARE( ui_img_gif_10_png);   // assets/gif_10.png

// FONTS
LV_FONT_DECLARE( ui_font_zh_14_bpp4);
LV_FONT_DECLARE( ui_font_zh_16_bpp4);
LV_FONT_DECLARE( ui_font_zh__8_bpp8);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
